// Generated by CoffeeScript 1.3.3
(function() {
  var $;

  $ = require("jquery");

  $.fn.ouija = function() {
    var self;
    self = this;
    this.hide();
    return this.each(function(i, select) {
      var $list, $planchette, $select, active, selected;
      $select = $(select);
      $select.after($list = $("<ul />").addClass("ouijaBoard"));
      selected = 0;
      active = false;
      $("option", $select).each(function(index) {
        var $option;
        $option = $(this);
        if ($option.is(":selected")) {
          selected = index;
        }
        return $list.append($("<li />").addClass("ouija-" + ($option.prop("value"))).text($option.text()).on({
          click: function() {
            var $li;
            $select.val($option.prop("value"));
            $select.trigger("change");
            $li = $(this);
            if (typeof active.removeClass === "function") {
              active.removeClass("on");
            }
            active = $li;
            return $planchette.animate({
              top: $li.position().top,
              left: $li.position().left,
              width: $li.width() + 5,
              height: $li.height() + 5
            }, 150, function() {
              $planchette.css({
                "-webkit-transform": $li.css("-webkit-transform")
              });
              $("li", $list).removeClass("on");
              return $li.addClass("on");
            });
          }
        }));
      });
      $list.append($planchette = $("<div />").addClass("planchette").css({
        height: $list.height()
      }));
      $planchette.on({
        click: function() {
          var first, next;
          next = active.nextAll("li").first();
          if (next.length) {
            return $(next).click();
          } else {
            first = active.prevAll("li").last();
            if (first.length) {
              return $(first).click();
            }
          }
        }
      });
      return $("li", $list).eq(selected).click();
    });
  };

  module.exports = function(selector) {
    return $(selector).ouija();
  };

}).call(this);
